import React, { useMemo, useState } from 'react';
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useApp } from '../context/AppContext';
import { colors, fonts } from '../theme';
import { Priority, RootStackParamList, Task } from '../types';

type Props = NativeStackScreenProps<RootStackParamList, 'Tasks'>;
type Filter = 'all' | 'active' | 'done';

const priorityColor: Record<Priority, string> = { high: colors.red, medium: colors.yellow, low: colors.blue };

function formatDue(date: string) {
  const value = new Date(date);
  return value.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) + ' · ' + value.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
}

function TaskRow({ task, onToggle, onDelete }: { task: Task; onToggle: () => void; onDelete: () => void }) {
  return <View style={[styles.task, task.completed && styles.taskDone]}><Pressable onPress={onToggle} style={[styles.check, task.completed && styles.checkDone]}><Text style={styles.checkText}>{task.completed ? '✓' : ''}</Text></Pressable><View style={styles.taskBody}><Text style={[styles.taskTitle, task.completed && styles.textDone]}>{task.title}</Text><Text numberOfLines={2} style={[styles.description, task.completed && styles.textDone]}>{task.description}</Text><View style={styles.meta}><View style={[styles.priority, { backgroundColor: priorityColor[task.priority] }]} /><Text style={styles.metaText}>{task.priority.toUpperCase()}  ·  {formatDue(task.dueAt)}</Text></View></View><Pressable accessibilityLabel="Delete task" onPress={onDelete} hitSlop={12}><Text style={styles.delete}>×</Text></Pressable></View>;
}

export function TasksScreen({ navigation }: Props) {
  const { user, tasks, logout, toggleTask, deleteTask } = useApp();
  const [filter, setFilter] = useState<Filter>('all');
  const visible = useMemo(() => tasks.filter(task => filter === 'all' || (filter === 'active' ? !task.completed : task.completed)).sort((a, b) => Number(a.completed) - Number(b.completed) || new Date(a.dueAt).getTime() - new Date(b.dueAt).getTime()), [tasks, filter]);
  const done = tasks.filter(task => task.completed).length;

  return <SafeAreaView style={styles.safe}><View style={styles.container}><View style={styles.header}><View><Text style={styles.eyebrow}>YOUR SPACE</Text><Text style={styles.heading}>Good to see you,</Text><Text style={styles.email}>{user?.email}</Text></View><Pressable onPress={logout} style={styles.avatar}><Text style={styles.avatarText}>{user?.email[0]?.toUpperCase()}</Text></Pressable></View><View style={styles.summary}><View><Text style={styles.summaryNumber}>{tasks.length - done}</Text><Text style={styles.summaryLabel}>open tasks</Text></View><View style={styles.summaryDivider} /><View><Text style={styles.summaryNumber}>{done}</Text><Text style={styles.summaryLabel}>completed</Text></View><Pressable onPress={() => navigation.navigate('AddTask')} style={styles.add}><Text style={styles.addText}>＋</Text></Pressable></View><View style={styles.filters}>{(['all', 'active', 'done'] as Filter[]).map(item => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item === 'all' ? 'Everything' : item === 'active' ? 'In progress' : 'Done'}</Text></Pressable>)}</View><FlatList data={visible} keyExtractor={item => item.id} renderItem={({ item }) => <TaskRow task={item} onToggle={() => toggleTask(item.id)} onDelete={() => deleteTask(item.id)} />} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>Nothing here yet</Text><Text style={styles.emptyText}>Add a task and give your next win a shape.</Text></View>} contentContainerStyle={visible.length ? styles.list : styles.emptyList} showsVerticalScrollIndicator={false} /></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, container: { flex: 1, paddingHorizontal: 22 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 18, paddingBottom: 22 }, eyebrow: { color: colors.green, fontSize: 11, fontWeight: '800', letterSpacing: 1.7 }, heading: { color: colors.ink, fontFamily: fonts.display, fontSize: 28, fontWeight: '800', marginTop: 4 }, email: { color: colors.muted, fontSize: 14, marginTop: 2 }, avatar: { backgroundColor: colors.greenSoft, borderRadius: 20, width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.green, fontWeight: '800', fontSize: 17 }, summary: { backgroundColor: colors.green, borderRadius: 20, padding: 20, flexDirection: 'row', alignItems: 'center' }, summaryNumber: { color: colors.white, fontSize: 29, fontWeight: '800' }, summaryLabel: { color: '#CBE7D8', fontSize: 12, marginTop: 2 }, summaryDivider: { height: 38, width: 1, backgroundColor: '#71AC8D', marginHorizontal: 22 }, add: { marginLeft: 'auto', backgroundColor: colors.white, width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, addText: { color: colors.green, fontSize: 28, lineHeight: 30 }, filters: { flexDirection: 'row', paddingVertical: 20, gap: 8 }, filter: { borderRadius: 12, paddingHorizontal: 13, paddingVertical: 9 }, filterActive: { backgroundColor: colors.ink }, filterText: { color: colors.muted, fontSize: 13, fontWeight: '700' }, filterTextActive: { color: colors.white }, list: { paddingBottom: 24 }, task: { backgroundColor: colors.white, borderRadius: 16, padding: 16, marginBottom: 10, flexDirection: 'row', alignItems: 'flex-start', borderWidth: 1, borderColor: colors.line }, taskDone: { opacity: 0.65 }, check: { borderColor: colors.green, borderWidth: 2, borderRadius: 8, width: 24, height: 24, alignItems: 'center', justifyContent: 'center', marginRight: 12, marginTop: 1 }, checkDone: { backgroundColor: colors.green }, checkText: { color: colors.white, fontWeight: '900' }, taskBody: { flex: 1 }, taskTitle: { color: colors.ink, fontSize: 16, fontWeight: '800' }, description: { color: colors.muted, fontSize: 13, lineHeight: 18, marginTop: 4 }, textDone: { textDecorationLine: 'line-through' }, meta: { flexDirection: 'row', alignItems: 'center', marginTop: 12 }, priority: { width: 7, height: 7, borderRadius: 4, marginRight: 7 }, metaText: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 0.4 }, delete: { color: colors.muted, fontSize: 24, lineHeight: 20, paddingLeft: 10 }, emptyList: { flexGrow: 1, justifyContent: 'center' }, empty: { alignItems: 'center', padding: 30 }, emptyTitle: { color: colors.ink, fontSize: 18, fontWeight: '800' }, emptyText: { color: colors.muted, textAlign: 'center', marginTop: 7, lineHeight: 20 },
});
